export const data = {
    CaptainAmerica:{
        one:{
            seats:50,
            noSeats:10
        },
        two:{
            seats:50,
            noSeats:10
        },
        three:{
            seats:50,
            noSeats:10
        },
        four:{
            seats:50,
            noSeats:10
        }
    },
    Titanic:{
        one:{
            seats:50,
            noSeats:10
        },
        two:{
            seats:50,
            noSeats:10
        },
        three:{
            seats:50,
            noSeats:10
        },
        four:{
            seats:50,
            noSeats:10
        }
    },
    Avengers:{
        one:{
            seats:50,
            noSeats:10
        },
        two:{
            seats:50,
            noSeats:10
        },
        three:{
            seats:50,
            noSeats:10
        },
        four:{
            seats:50,
            noSeats:10
        }
    },
    Avatar:{
        one:{
            seats:50,
            noSeats:10
        },
        two:{
            seats:50,
            noSeats:10
        },
        three:{
            seats:50,
            noSeats:10
        },
        four:{
            seats:50,
            noSeats:10
        }
    }
}